name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy latest code
        run: |
          cd /var/www/20kbphoto
          git fetch origin main
          git reset --hard origin/main
          npm ci
          npm run build
          sudo systemctl reload nginx
